import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { colors } from '../styles/theme'
import Button from "@/components/Button";
import Github from "@/components/Icons/Github"; 
import { LoginWithGitHub, onAuthStateChanged } from "@/firebase/client";
import { useState, useEffect } from "react";
import Avatar from "@/components/Avatar";
import Logo from "@/components/Icons/Logo";
import { useRouter } from "next/router";
import  userUser, { USER_STATES } from "@/hooks/useUser";



const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const user = userUser();

  useEffect(() => {
    user && router.replace('/home')
  }, [user])

  const handleClick = () => {
    LoginWithGitHub()
      .catch(err => console.log(err));
  }



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section> 
        <Logo width="100" />
        <h1 className={styles.code}>Devter</h1>
        <h2 className={styles.description}>Talk abour developers</h2>
        <div> 
          {user === USER_STATES.NOT_LOGGED &&
          <Button onClick={handleClick}>
            <Github fill='#fff' width={24} height={24} />
            Login with Github
          </Button>
          }
          {user === USER_STATES.NOT_KNOWN && <img src="/spinner.gif" alt="spinner" />}
          {user && user.username &&
          <div>
            <Avatar src={user.avatar} alt={user.username} text={user.username} withText={true} />
          </div>
          }
        </div>
      </section>
      <Link href="/timeline">timeline</Link>

      <style jsx>{`
        img {
          width: 120px;
        }

        h1 {
          color: ${colors.primary};
          font-size: 24px;
        }
        
        h2 {
          color: ${colors.secondary};
          font-size: 16px;
        }

        section {
          display: grid;
          height: 100%;
          place-items: center;
          place-content: center;
        }
      `}</style>
    
    </>
  );
}
